[package]
name = "wordle-pokemon"
version = "0.1.0"
authors = ["Keigo Habara <k.habara.aa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.6"
ord_subset = "3"
rayon = "1.5"